// This file is auto-generated by update-dashboard.js
// Do not edit this file directly - it will be overwritten

window.dashboardData = {
  "lastUpdated": "2025-03-03",
  "milestones": {
    "total": 11,
    "completed": 5,
    "inProgress": 2,
    "planned": 4
  },
  "tasks": {
    "total": 13,
    "completed": 5,
    "inProgress": 3,
    "pending": 5
  },
  "tests": {
    "total": 104,
    "passing": 34,
    "failing": 67,
    "hanging": 3
  },
  "brqs": {
    "total": 20,
    "completed": 1,
    "inProgress": 4,
    "notStarted": 15
  },
  "currentSprint": {
    "name": "Service Integration Architecture",
    "progress": 78,
    "tasks": [
      {
        "id": "task-1",
        "name": "Service Discovery Implementation",
        "status": "completed",
        "sprint": "Service Integration Architecture",
        "milestone": "milestone-6",
        "brq": "MEXP-2025-007-BE",
        "assignee": "Developer Team",
        "tests": [
          "service-discovery.test.ts"
        ]
      },
      {
        "id": "task-2",
        "name": "Cross-Service Authentication",
        "status": "completed",
        "sprint": "Service Integration Architecture",
        "milestone": "milestone-6",
        "brq": "MEXP-2025-007-BE",
        "assignee": "Security Team",
        "tests": [
          "cross-service-auth.test.ts"
        ]
      },
      {
        "id": "task-3",
        "name": "Service Deployments",
        "status": "completed",
        "sprint": "Service Integration Architecture",
        "milestone": "milestone-6",
        "brq": "MEXP-2025-007-BE",
        "assignee": "DevOps Team",
        "tests": [
          "container-runtime.test.ts",
          "istio-client.test.ts",
          "istio-client.additional.test.ts"
        ]
      },
      {
        "id": "task-4",
        "name": "Service Mesh Configuration",
        "status": "in-progress",
        "sprint": "Service Integration Architecture",
        "milestone": "milestone-6",
        "brq": "MEXP-2025-007-BE",
        "assignee": "DevOps Team",
        "tests": [
          "service-mesh.test.ts"
        ],
        "progress": 70
      },
      {
        "id": "task-5",
        "name": "Deployment Configuration",
        "status": "in-progress",
        "sprint": "Service Integration Architecture",
        "milestone": "milestone-6",
        "brq": "MEXP-2025-007-BE",
        "assignee": "DevOps Team",
        "tests": [
          "service-deployment.test.ts"
        ],
        "progress": 85
      },
      {
        "id": "task-6",
        "name": "Kubernetes Configuration",
        "status": "pending",
        "sprint": "Service Integration Architecture",
        "milestone": "milestone-6",
        "brq": "MEXP-2025-007-BE",
        "assignee": "Unassigned",
        "tests": [
          "kubernetes-config.test.ts"
        ],
        "progress": 0
      },
      {
        "id": "task-7",
        "name": "Documentation and Examples",
        "status": "pending",
        "sprint": "Service Integration Architecture",
        "milestone": "milestone-6",
        "brq": "MEXP-2025-007-BE",
        "assignee": "Unassigned",
        "progress": 0
      },
      {
        "id": "task-8",
        "name": "Integration Testing",
        "status": "pending",
        "sprint": "Service Integration Architecture",
        "milestone": "milestone-6",
        "brq": "MEXP-2025-007-BE",
        "assignee": "QA Team",
        "progress": 0
      }
    ]
  },
  "allMilestones": [
    {
      "id": "milestone-1",
      "name": "Core Infrastructure",
      "status": "completed",
      "quarter": "q1-2025",
      "progress": 100,
      "brqs": [
        "MEXP-2025-003-BE",
        "MEXP-2025-024-INFRA",
        "MEXP-2025-025-INFRA"
      ]
    },
    {
      "id": "milestone-2",
      "name": "Authentication & Security",
      "status": "completed",
      "quarter": "q1-2025",
      "progress": 100,
      "brqs": [
        "MEXP-2025-002-BE"
      ]
    },
    {
      "id": "milestone-3",
      "name": "API Integration Foundation",
      "status": "completed",
      "quarter": "q1-2025",
      "progress": 100,
      "brqs": [
        "MEXP-2025-001-API",
        "MEXP-2025-006-API"
      ]
    },
    {
      "id": "milestone-4",
      "name": "Core Services",
      "status": "completed",
      "quarter": "q1-2025",
      "progress": 100,
      "brqs": [
        "MEXP-2025-004-BE",
        "MEXP-2025-008-BE",
        "MEXP-2025-027-BE"
      ]
    },
    {
      "id": "milestone-5",
      "name": "External Integrations",
      "status": "completed",
      "quarter": "q1-2025",
      "progress": 100,
      "brqs": [
        "MEXP-2025-030-API",
        "MEXP-2025-031-API"
      ]
    },
    {
      "id": "milestone-6",
      "name": "Service Integration Architecture",
      "status": "in-progress",
      "quarter": "q2-2025",
      "progress": 77.8,
      "brqs": [
        "MEXP-2025-007-BE"
      ]
    },
    {
      "id": "milestone-7",
      "name": "Frontend Architecture",
      "status": "in-progress",
      "quarter": "q2-2025",
      "progress": 50,
      "brqs": [
        "MEXP-2025-002-FE",
        "MEXP-2025-005-FE",
        "MEXP-2025-018-FE"
      ]
    },
    {
      "id": "milestone-8",
      "name": "Dashboards & Analytics",
      "status": "planned",
      "quarter": "q3-2025",
      "progress": 0,
      "brqs": [
        "MEXP-2025-040-FE"
      ]
    },
    {
      "id": "milestone-9",
      "name": "MVP Implementation",
      "status": "planned",
      "quarter": "q3-2025",
      "progress": 0,
      "brqs": [
        "MEXP-2025-037-FULL"
      ]
    },
    {
      "id": "milestone-10",
      "name": "MontPC CRM Integration",
      "status": "planned",
      "quarter": "q4-2025",
      "progress": 0,
      "brqs": [
        "MONT-2025-001-FULL",
        "MONT-2025-002-FULL"
      ]
    },
    {
      "id": "milestone-11",
      "name": "Emergency Recovery System",
      "status": "planned",
      "quarter": "q4-2025",
      "progress": 0,
      "brqs": [
        "MONT-2025-007-FULL",
        "MONT-2025-032-API"
      ]
    }
  ],
  "allBrqs": [
    {
      "id": "MEXP-2025-001-API",
      "name": "API Integration Phase",
      "tests": 3,
      "priority": "P0",
      "status": "in-progress",
      "progress": 33.3,
      "milestone": "API Integration Foundation"
    },
    {
      "id": "MEXP-2025-002-BE",
      "name": "Authentication & Security",
      "tests": 4,
      "priority": "P0",
      "status": "in-progress",
      "progress": 75,
      "milestone": "Authentication & Security"
    },
    {
      "id": "MEXP-2025-003-BE",
      "name": "Message Queue System",
      "tests": 5,
      "priority": "P0",
      "status": "in-progress",
      "progress": 80,
      "milestone": "Core Infrastructure"
    },
    {
      "id": "MEXP-2025-004-BE",
      "name": "Core CRUD Functionality",
      "tests": 3,
      "priority": "P0",
      "status": "planned",
      "progress": 0,
      "milestone": "Core Services"
    },
    {
      "id": "MEXP-2025-005-FE",
      "name": "UI Architecture",
      "tests": 1,
      "priority": "P1",
      "status": "planned",
      "progress": 0,
      "milestone": "Frontend Architecture"
    },
    {
      "id": "MEXP-2025-006-API",
      "name": "Customer CRUD API",
      "tests": 3,
      "priority": "P0",
      "status": "planned",
      "progress": 0,
      "milestone": "API Integration Foundation"
    },
    {
      "id": "MEXP-2025-007-BE",
      "name": "Service Integration Architecture",
      "tests": 9,
      "priority": "P0",
      "status": "in-progress",
      "progress": 66.7,
      "milestone": "Service Integration Architecture"
    },
    {
      "id": "MEXP-2025-008-BE",
      "name": "Customer Management System",
      "tests": 2,
      "priority": "P0",
      "status": "completed",
      "progress": 100,
      "milestone": "Core Services"
    },
    {
      "id": "MEXP-2025-018-FE",
      "name": "Frontend Test Architecture",
      "tests": 1,
      "priority": "P2",
      "status": "planned",
      "progress": 0,
      "milestone": "Frontend Architecture"
    },
    {
      "id": "MEXP-2025-024-INFRA",
      "name": "MVP Readiness",
      "tests": 3,
      "priority": "P3",
      "status": "planned",
      "progress": 0,
      "milestone": "Core Infrastructure"
    },
    {
      "id": "MEXP-2025-025-INFRA",
      "name": "Infrastructure Simplification",
      "tests": 3,
      "priority": "P3",
      "status": "planned",
      "progress": 0,
      "milestone": "Core Infrastructure"
    },
    {
      "id": "MEXP-2025-027-BE",
      "name": "Product Catalog",
      "tests": 3,
      "priority": "P1",
      "status": "planned",
      "progress": 0,
      "milestone": "Core Services"
    },
    {
      "id": "MEXP-2025-030-API",
      "name": "External API Integrations",
      "tests": 3,
      "priority": "P1",
      "status": "planned",
      "progress": 0,
      "milestone": "External Integrations"
    },
    {
      "id": "MEXP-2025-031-API",
      "name": "Ringover Customer Management",
      "tests": 3,
      "priority": "P1",
      "status": "planned",
      "progress": 0,
      "milestone": "External Integrations"
    },
    {
      "id": "MEXP-2025-037-FULL",
      "name": "MVP Implementation",
      "tests": 3,
      "priority": "P3",
      "status": "planned",
      "progress": 0,
      "milestone": "MVP Implementation"
    },
    {
      "id": "MEXP-2025-040-FE",
      "name": "Dashboard Design",
      "tests": 1,
      "priority": "P2",
      "status": "planned",
      "progress": 0,
      "milestone": "Dashboards & Analytics"
    },
    {
      "id": "MONT-2025-001-FULL",
      "name": "Customer Service Implementation",
      "tests": 2,
      "priority": "P0",
      "status": "planned",
      "progress": 0,
      "milestone": "MontPC CRM Integration"
    },
    {
      "id": "MONT-2025-002-FULL",
      "name": "Auth Service & Frontend",
      "tests": 5,
      "priority": "P1",
      "status": "planned",
      "progress": 0,
      "milestone": "MontPC CRM Integration"
    },
    {
      "id": "MONT-2025-007-FULL",
      "name": "Emergency Recovery",
      "tests": 0,
      "priority": "P1",
      "status": "planned",
      "progress": 0,
      "milestone": "Emergency Recovery System"
    },
    {
      "id": "MONT-2025-032-API",
      "name": "External Integrations",
      "tests": 1,
      "priority": "P2",
      "status": "planned",
      "progress": 0,
      "milestone": "Emergency Recovery System"
    }
  ],
  "allTasks": [
    {
      "id": "task-1",
      "name": "Service Discovery Implementation",
      "status": "completed",
      "sprint": "Service Integration Architecture",
      "milestone": "milestone-6",
      "brq": "MEXP-2025-007-BE",
      "assignee": "Developer Team",
      "tests": [
        "service-discovery.test.ts"
      ]
    },
    {
      "id": "task-2",
      "name": "Cross-Service Authentication",
      "status": "completed",
      "sprint": "Service Integration Architecture",
      "milestone": "milestone-6",
      "brq": "MEXP-2025-007-BE",
      "assignee": "Security Team",
      "tests": [
        "cross-service-auth.test.ts"
      ]
    },
    {
      "id": "task-3",
      "name": "Service Deployments",
      "status": "completed",
      "sprint": "Service Integration Architecture",
      "milestone": "milestone-6",
      "brq": "MEXP-2025-007-BE",
      "assignee": "DevOps Team",
      "tests": [
        "container-runtime.test.ts",
        "istio-client.test.ts",
        "istio-client.additional.test.ts"
      ]
    },
    {
      "id": "task-4",
      "name": "Service Mesh Configuration",
      "status": "in-progress",
      "sprint": "Service Integration Architecture",
      "milestone": "milestone-6",
      "brq": "MEXP-2025-007-BE",
      "assignee": "DevOps Team",
      "tests": [
        "service-mesh.test.ts"
      ],
      "progress": 70
    },
    {
      "id": "task-5",
      "name": "Deployment Configuration",
      "status": "in-progress",
      "sprint": "Service Integration Architecture",
      "milestone": "milestone-6",
      "brq": "MEXP-2025-007-BE",
      "assignee": "DevOps Team",
      "tests": [
        "service-deployment.test.ts"
      ],
      "progress": 85
    },
    {
      "id": "task-6",
      "name": "Kubernetes Configuration",
      "status": "pending",
      "sprint": "Service Integration Architecture",
      "milestone": "milestone-6",
      "brq": "MEXP-2025-007-BE",
      "assignee": "Unassigned",
      "tests": [
        "kubernetes-config.test.ts"
      ],
      "progress": 0
    },
    {
      "id": "task-7",
      "name": "Documentation and Examples",
      "status": "pending",
      "sprint": "Service Integration Architecture",
      "milestone": "milestone-6",
      "brq": "MEXP-2025-007-BE",
      "assignee": "Unassigned",
      "progress": 0
    },
    {
      "id": "task-8",
      "name": "Integration Testing",
      "status": "pending",
      "sprint": "Service Integration Architecture",
      "milestone": "milestone-6",
      "brq": "MEXP-2025-007-BE",
      "assignee": "QA Team",
      "progress": 0
    },
    {
      "id": "task-9",
      "name": "Component Library Setup",
      "status": "completed",
      "sprint": "Frontend Architecture",
      "milestone": "milestone-7",
      "brq": "MEXP-2025-005-FE",
      "assignee": "UI Team",
      "tests": [
        "component-tests.test.js"
      ]
    },
    {
      "id": "task-10",
      "name": "React Application Architecture",
      "status": "completed",
      "sprint": "Frontend Architecture",
      "milestone": "milestone-7",
      "brq": "MEXP-2025-005-FE",
      "assignee": "Frontend Team"
    },
    {
      "id": "task-11",
      "name": "Frontend Testing Framework",
      "status": "in-progress",
      "sprint": "Frontend Architecture",
      "milestone": "milestone-7",
      "brq": "MEXP-2025-018-FE",
      "assignee": "Frontend Team",
      "tests": [
        "styling-consistency.test.tsx"
      ],
      "progress": 40
    },
    {
      "id": "task-12",
      "name": "Responsive UI Components",
      "status": "pending",
      "sprint": "Frontend Architecture",
      "milestone": "milestone-7",
      "brq": "MEXP-2025-002-FE",
      "assignee": "Unassigned",
      "progress": 0
    },
    {
      "id": "task-13",
      "name": "Storybook Documentation",
      "status": "pending",
      "sprint": "Frontend Architecture",
      "milestone": "milestone-7",
      "brq": "MEXP-2025-005-FE",
      "assignee": "Unassigned",
      "progress": 0
    }
  ],
  "testsByPriority": {
    "p0": {
      "total": 25,
      "passing": 21,
      "failing": 4,
      "success": 84
    },
    "p1": {
      "total": 21,
      "passing": 8,
      "failing": 13,
      "success": 38.1
    },
    "p2": {
      "total": 16,
      "passing": 5,
      "failing": 11,
      "success": 31.3
    },
    "p3": {
      "total": 17,
      "passing": 0,
      "failing": 14,
      "hanging": 3,
      "success": 0
    }
  },
  "recentUpdates": [
    {
      "date": "2025-03-03",
      "type": "Milestone",
      "description": "Completed milestone: Core Infrastructure",
      "status": "completed"
    },
    {
      "date": "2025-03-03",
      "type": "Milestone",
      "description": "Completed milestone: Authentication & Security",
      "status": "completed"
    },
    {
      "date": "2025-03-03",
      "type": "Milestone",
      "description": "Completed milestone: API Integration Foundation",
      "status": "completed"
    },
    {
      "date": "2025-03-03",
      "type": "Task",
      "description": "Completed task: Service Discovery Implementation",
      "status": "completed"
    },
    {
      "date": "2025-03-03",
      "type": "Task",
      "description": "Completed task: Cross-Service Authentication",
      "status": "completed"
    }
  ],
  "recentTestFixes": [
    {
      "test": "Test 1",
      "date": "2025-03-03",
      "brq": "-",
      "description": "Initial setup of test dashboard with accurate status reporting"
    }
  ],
  "allTests": [
    {
      "id": 1,
      "name": "mexp-2025-001-api-test-1.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-001-API",
      "status": "passing",
      "path": "/tests/p0/mexp-2025-001-api-test-1.test.ts"
    },
    {
      "id": 2,
      "name": "mexp-2025-001-api-test-2.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-001-API",
      "status": "failing",
      "path": "/tests/p0/mexp-2025-001-api-test-2.test.ts"
    },
    {
      "id": 3,
      "name": "mexp-2025-001-api-test-3.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-001-API",
      "status": "failing",
      "path": "/tests/p0/mexp-2025-001-api-test-3.test.ts"
    },
    {
      "id": 4,
      "name": "permissions.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-002-BE",
      "status": "passing",
      "path": "/tests/p0/permissions.test.ts"
    },
    {
      "id": 5,
      "name": "mexp-2025-002-be-test-2.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-002-BE",
      "status": "passing",
      "path": "/tests/p0/mexp-2025-002-be-test-2.test.ts"
    },
    {
      "id": 6,
      "name": "mexp-2025-002-be-test-3.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-002-BE",
      "status": "passing",
      "path": "/tests/p0/mexp-2025-002-be-test-3.test.ts"
    },
    {
      "id": 7,
      "name": "mexp-2025-002-be-test-4.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-002-BE",
      "status": "failing",
      "path": "/tests/p0/mexp-2025-002-be-test-4.test.ts"
    },
    {
      "id": 8,
      "name": "queue-retry.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-003-BE",
      "status": "passing",
      "path": "/tests/p0/queue-retry.test.ts"
    },
    {
      "id": 9,
      "name": "mexp-2025-003-be-test-2.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-003-BE",
      "status": "passing",
      "path": "/tests/p0/mexp-2025-003-be-test-2.test.ts"
    },
    {
      "id": 10,
      "name": "mexp-2025-003-be-test-3.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-003-BE",
      "status": "passing",
      "path": "/tests/p0/mexp-2025-003-be-test-3.test.ts"
    },
    {
      "id": 11,
      "name": "mexp-2025-003-be-test-4.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-003-BE",
      "status": "passing",
      "path": "/tests/p0/mexp-2025-003-be-test-4.test.ts"
    },
    {
      "id": 12,
      "name": "mexp-2025-003-be-test-5.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-003-BE",
      "status": "failing",
      "path": "/tests/p0/mexp-2025-003-be-test-5.test.ts"
    },
    {
      "id": 13,
      "name": "mexp-2025-004-be-test-1.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-004-BE",
      "status": "failing",
      "path": "/tests/p0/mexp-2025-004-be-test-1.test.ts"
    },
    {
      "id": 14,
      "name": "mexp-2025-004-be-test-2.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-004-BE",
      "status": "failing",
      "path": "/tests/p0/mexp-2025-004-be-test-2.test.ts"
    },
    {
      "id": 15,
      "name": "mexp-2025-004-be-test-3.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-004-BE",
      "status": "failing",
      "path": "/tests/p0/mexp-2025-004-be-test-3.test.ts"
    },
    {
      "id": 16,
      "name": "mexp-2025-005-fe-test-1.test.ts",
      "priority": "P1",
      "project": "mExpress",
      "brq": "MEXP-2025-005-FE",
      "status": "failing",
      "path": "/tests/p1/mexp-2025-005-fe-test-1.test.ts"
    },
    {
      "id": 17,
      "name": "mexp-2025-006-api-test-1.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-006-API",
      "status": "failing",
      "path": "/tests/p0/mexp-2025-006-api-test-1.test.ts"
    },
    {
      "id": 18,
      "name": "mexp-2025-006-api-test-2.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-006-API",
      "status": "failing",
      "path": "/tests/p0/mexp-2025-006-api-test-2.test.ts"
    },
    {
      "id": 19,
      "name": "mexp-2025-006-api-test-3.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-006-API",
      "status": "failing",
      "path": "/tests/p0/mexp-2025-006-api-test-3.test.ts"
    },
    {
      "id": 20,
      "name": "cross-service-auth.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-007-BE",
      "status": "passing",
      "path": "/tests/p0/cross-service-auth.test.ts"
    },
    {
      "id": 21,
      "name": "mexp-2025-007-be-test-2.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-007-BE",
      "status": "passing",
      "path": "/tests/p0/mexp-2025-007-be-test-2.test.ts"
    },
    {
      "id": 22,
      "name": "mexp-2025-007-be-test-3.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-007-BE",
      "status": "passing",
      "path": "/tests/p0/mexp-2025-007-be-test-3.test.ts"
    },
    {
      "id": 23,
      "name": "mexp-2025-007-be-test-4.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-007-BE",
      "status": "passing",
      "path": "/tests/p0/mexp-2025-007-be-test-4.test.ts"
    },
    {
      "id": 24,
      "name": "mexp-2025-007-be-test-5.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-007-BE",
      "status": "passing",
      "path": "/tests/p0/mexp-2025-007-be-test-5.test.ts"
    },
    {
      "id": 25,
      "name": "mexp-2025-007-be-test-6.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-007-BE",
      "status": "passing",
      "path": "/tests/p0/mexp-2025-007-be-test-6.test.ts"
    },
    {
      "id": 26,
      "name": "service-deployment.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-007-BE",
      "status": "failing",
      "path": "/tests/p0/service-deployment.test.ts"
    },
    {
      "id": 27,
      "name": "mexp-2025-007-be-test-8.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-007-BE",
      "status": "failing",
      "path": "/tests/p0/mexp-2025-007-be-test-8.test.ts"
    },
    {
      "id": 28,
      "name": "mexp-2025-007-be-test-9.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-007-BE",
      "status": "failing",
      "path": "/tests/p0/mexp-2025-007-be-test-9.test.ts"
    },
    {
      "id": 29,
      "name": "customer-validation.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-008-BE",
      "status": "passing",
      "path": "/tests/p0/customer-validation.test.ts"
    },
    {
      "id": 30,
      "name": "mexp-2025-008-be-test-2.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-008-BE",
      "status": "passing",
      "path": "/tests/p0/mexp-2025-008-be-test-2.test.ts"
    },
    {
      "id": 31,
      "name": "mexp-2025-018-fe-test-1.test.ts",
      "priority": "P2",
      "project": "mExpress",
      "brq": "MEXP-2025-018-FE",
      "status": "failing",
      "path": "/tests/p2/mexp-2025-018-fe-test-1.test.ts"
    },
    {
      "id": 32,
      "name": "mexp-2025-024-infra-test-1.test.ts",
      "priority": "P3",
      "project": "mExpress",
      "brq": "MEXP-2025-024-INFRA",
      "status": "failing",
      "path": "/tests/p3/mexp-2025-024-infra-test-1.test.ts"
    },
    {
      "id": 33,
      "name": "mexp-2025-024-infra-test-2.test.ts",
      "priority": "P3",
      "project": "mExpress",
      "brq": "MEXP-2025-024-INFRA",
      "status": "failing",
      "path": "/tests/p3/mexp-2025-024-infra-test-2.test.ts"
    },
    {
      "id": 34,
      "name": "mexp-2025-024-infra-test-3.test.ts",
      "priority": "P3",
      "project": "mExpress",
      "brq": "MEXP-2025-024-INFRA",
      "status": "failing",
      "path": "/tests/p3/mexp-2025-024-infra-test-3.test.ts"
    },
    {
      "id": 35,
      "name": "mexp-2025-025-infra-test-1.test.ts",
      "priority": "P3",
      "project": "mExpress",
      "brq": "MEXP-2025-025-INFRA",
      "status": "failing",
      "path": "/tests/p3/mexp-2025-025-infra-test-1.test.ts"
    },
    {
      "id": 36,
      "name": "mexp-2025-025-infra-test-2.test.ts",
      "priority": "P3",
      "project": "mExpress",
      "brq": "MEXP-2025-025-INFRA",
      "status": "failing",
      "path": "/tests/p3/mexp-2025-025-infra-test-2.test.ts"
    },
    {
      "id": 37,
      "name": "mexp-2025-025-infra-test-3.test.ts",
      "priority": "P3",
      "project": "mExpress",
      "brq": "MEXP-2025-025-INFRA",
      "status": "failing",
      "path": "/tests/p3/mexp-2025-025-infra-test-3.test.ts"
    },
    {
      "id": 38,
      "name": "mexp-2025-027-be-test-1.test.ts",
      "priority": "P1",
      "project": "mExpress",
      "brq": "MEXP-2025-027-BE",
      "status": "failing",
      "path": "/tests/p1/mexp-2025-027-be-test-1.test.ts"
    },
    {
      "id": 39,
      "name": "mexp-2025-027-be-test-2.test.ts",
      "priority": "P1",
      "project": "mExpress",
      "brq": "MEXP-2025-027-BE",
      "status": "failing",
      "path": "/tests/p1/mexp-2025-027-be-test-2.test.ts"
    },
    {
      "id": 40,
      "name": "mexp-2025-027-be-test-3.test.ts",
      "priority": "P1",
      "project": "mExpress",
      "brq": "MEXP-2025-027-BE",
      "status": "failing",
      "path": "/tests/p1/mexp-2025-027-be-test-3.test.ts"
    },
    {
      "id": 41,
      "name": "mexp-2025-030-api-test-1.test.ts",
      "priority": "P1",
      "project": "mExpress",
      "brq": "MEXP-2025-030-API",
      "status": "failing",
      "path": "/tests/p1/mexp-2025-030-api-test-1.test.ts"
    },
    {
      "id": 42,
      "name": "mexp-2025-030-api-test-2.test.ts",
      "priority": "P1",
      "project": "mExpress",
      "brq": "MEXP-2025-030-API",
      "status": "failing",
      "path": "/tests/p1/mexp-2025-030-api-test-2.test.ts"
    },
    {
      "id": 43,
      "name": "mexp-2025-030-api-test-3.test.ts",
      "priority": "P1",
      "project": "mExpress",
      "brq": "MEXP-2025-030-API",
      "status": "failing",
      "path": "/tests/p1/mexp-2025-030-api-test-3.test.ts"
    },
    {
      "id": 44,
      "name": "mexp-2025-031-api-test-1.test.ts",
      "priority": "P1",
      "project": "mExpress",
      "brq": "MEXP-2025-031-API",
      "status": "failing",
      "path": "/tests/p1/mexp-2025-031-api-test-1.test.ts"
    },
    {
      "id": 45,
      "name": "mexp-2025-031-api-test-2.test.ts",
      "priority": "P1",
      "project": "mExpress",
      "brq": "MEXP-2025-031-API",
      "status": "failing",
      "path": "/tests/p1/mexp-2025-031-api-test-2.test.ts"
    },
    {
      "id": 46,
      "name": "mexp-2025-031-api-test-3.test.ts",
      "priority": "P1",
      "project": "mExpress",
      "brq": "MEXP-2025-031-API",
      "status": "failing",
      "path": "/tests/p1/mexp-2025-031-api-test-3.test.ts"
    },
    {
      "id": 47,
      "name": "mexp-2025-037-full-test-1.test.ts",
      "priority": "P3",
      "project": "mExpress",
      "brq": "MEXP-2025-037-FULL",
      "status": "failing",
      "path": "/tests/p3/mexp-2025-037-full-test-1.test.ts"
    },
    {
      "id": 48,
      "name": "mexp-2025-037-full-test-2.test.ts",
      "priority": "P3",
      "project": "mExpress",
      "brq": "MEXP-2025-037-FULL",
      "status": "failing",
      "path": "/tests/p3/mexp-2025-037-full-test-2.test.ts"
    },
    {
      "id": 49,
      "name": "mexp-2025-037-full-test-3.test.ts",
      "priority": "P3",
      "project": "mExpress",
      "brq": "MEXP-2025-037-FULL",
      "status": "failing",
      "path": "/tests/p3/mexp-2025-037-full-test-3.test.ts"
    },
    {
      "id": 50,
      "name": "mexp-2025-040-fe-test-1.test.ts",
      "priority": "P2",
      "project": "mExpress",
      "brq": "MEXP-2025-040-FE",
      "status": "failing",
      "path": "/tests/p2/mexp-2025-040-fe-test-1.test.ts"
    },
    {
      "id": 51,
      "name": "customer-repair.test.ts",
      "priority": "P0",
      "project": "MontPC",
      "brq": "MONT-2025-001-FULL",
      "status": "failing",
      "path": "/tests/p0/customer-repair.test.ts"
    },
    {
      "id": 52,
      "name": "mont-2025-001-full-test-2.test.ts",
      "priority": "P0",
      "project": "MontPC",
      "brq": "MONT-2025-001-FULL",
      "status": "failing",
      "path": "/tests/p0/mont-2025-001-full-test-2.test.ts"
    },
    {
      "id": 53,
      "name": "auth-components.test.tsx",
      "priority": "P1",
      "project": "MontPC",
      "brq": "MONT-2025-002-FULL",
      "status": "failing",
      "path": "/tests/p1/auth-components.test.tsx"
    },
    {
      "id": 54,
      "name": "mont-2025-002-full-test-2.test.ts",
      "priority": "P1",
      "project": "MontPC",
      "brq": "MONT-2025-002-FULL",
      "status": "failing",
      "path": "/tests/p1/mont-2025-002-full-test-2.test.ts"
    },
    {
      "id": 55,
      "name": "mont-2025-002-full-test-3.test.ts",
      "priority": "P1",
      "project": "MontPC",
      "brq": "MONT-2025-002-FULL",
      "status": "failing",
      "path": "/tests/p1/mont-2025-002-full-test-3.test.ts"
    },
    {
      "id": 56,
      "name": "mont-2025-002-full-test-4.test.ts",
      "priority": "P1",
      "project": "MontPC",
      "brq": "MONT-2025-002-FULL",
      "status": "failing",
      "path": "/tests/p1/mont-2025-002-full-test-4.test.ts"
    },
    {
      "id": 57,
      "name": "mont-2025-002-full-test-5.test.ts",
      "priority": "P1",
      "project": "MontPC",
      "brq": "MONT-2025-002-FULL",
      "status": "failing",
      "path": "/tests/p1/mont-2025-002-full-test-5.test.ts"
    },
    {
      "id": 58,
      "name": "mont-2025-032-api-test-1.test.ts",
      "priority": "P2",
      "project": "MontPC",
      "brq": "MONT-2025-032-API",
      "status": "failing",
      "path": "/tests/p2/mont-2025-032-api-test-1.test.ts"
    },
    {
      "id": 59,
      "name": "kubernetes-config.test.ts",
      "priority": "P0",
      "project": "mExpress",
      "brq": "MEXP-2025-024-INFRA",
      "status": "failing",
      "path": "/tests/p0/kubernetes-config.test.ts"
    },
    {
      "id": 60,
      "name": "message-queue-v2.test.ts",
      "priority": "P1",
      "project": "mExpress",
      "brq": "MEXP-2025-003-BE",
      "status": "failing",
      "path": "/tests/p1/message-queue-v2.test.ts"
    },
    {
      "id": 61,
      "name": "message-queue-stress.test.ts",
      "priority": "P2",
      "project": "mExpress",
      "brq": "MEXP-2025-003-BE",
      "status": "failing",
      "path": "/tests/p2/message-queue-stress.test.ts"
    },
    {
      "id": 62,
      "name": "product-events.test.ts",
      "priority": "P2",
      "project": "mExpress",
      "brq": "MEXP-2025-027-BE",
      "status": "failing",
      "path": "/tests/p2/product-events.test.ts"
    },
    {
      "id": 63,
      "name": "merge.spec.ts",
      "priority": "P1",
      "project": "mExpress",
      "brq": "MEXP-2025-004-BE",
      "status": "failing",
      "path": "/tests/p1/merge.spec.ts"
    },
    {
      "id": 64,
      "name": "customer-search.test.ts",
      "priority": "P3",
      "project": "mExpress",
      "brq": "MEXP-2025-008-BE",
      "status": "failing",
      "path": "/tests/p3/customer-search.test.ts"
    },
    {
      "id": 65,
      "name": "repair-status.test.ts",
      "priority": "P1",
      "project": "MontPC",
      "brq": "MONT-2025-001-FULL",
      "status": "failing",
      "path": "/tests/p1/repair-status.test.ts"
    },
    {
      "id": 66,
      "name": "login.test.tsx",
      "priority": "P0",
      "project": "MontPC",
      "brq": "MONT-2025-002-FULL",
      "status": "failing",
      "path": "/tests/p0/login.test.tsx"
    },
    {
      "id": 67,
      "name": "password-reset.test.tsx",
      "priority": "P2",
      "project": "MontPC",
      "brq": "MONT-2025-002-FULL",
      "status": "failing",
      "path": "/tests/p2/password-reset.test.tsx"
    },
    {
      "id": 68,
      "name": "emergency-recovery.test.ts",
      "priority": "P3",
      "project": "MontPC",
      "brq": "MONT-2025-007-FULL",
      "status": "failing",
      "path": "/tests/p3/emergency-recovery.test.ts"
    },
    {
      "id": 69,
      "name": "istio-client.additional.test.ts",
      "priority": "P1",
      "project": "mExpress",
      "brq": "MEXP-2025-007-BE",
      "status": "passing",
      "path": "/tests/p1/istio-client.additional.test.ts"
    },
    {
      "id": 70,
      "name": "auth.service.unit.test.ts",
      "priority": "P0",
      "project": "MontPC",
      "brq": "MONT-2025-002-FULL",
      "status": "passing",
      "path": "/tests/p0/auth.service.unit.test.ts"
    },
    {
      "id": 71,
      "name": "customer.service.test.ts",
      "priority": "P0",
      "project": "MontPC",
      "brq": "MONT-2025-001-FULL",
      "status": "passing",
      "path": "/tests/p0/customer.service.test.ts"
    }
  ]
};