#!/bin/bash

# b_project_test_runner.sh
#
# This script runs tests for a specific project and updates the test status in real-time
# It uses the PROJECT_TESTS_LIST.md file generated by a_project_test_pre_calculation.sh
#
# Usage: ./b_project_test_runner.sh [project_name] [options]
# Options:
#   --max-tests=N      Maximum number of tests to run
#   --all              Run all tests (default: only run newer tests)
#   --shuffle          Shuffle test order
#   --priority=P0,P1   Only run tests with specified priorities (comma-separated)
#
# Example: ./b_project_test_runner.sh jerome_bikes --priority=P0,P1

# Check if project name is provided
if [ -z "$1" ]; then
  echo "Error: Project name is required."
  echo "Usage: ./b_project_test_runner.sh [project_name] [options]"
  echo "Example: ./b_project_test_runner.sh jerome_bikes --priority=P0,P1"
  exit 1
fi

PROJECT_NAME="$1"
shift # Remove project name from arguments

# Validate project directory exists
if [ ! -d "/opt/mExpress/projects/$PROJECT_NAME" ] && [ ! -d "/opt/mExpress/packages/$PROJECT_NAME" ]; then
  echo "Error: Project directory not found: /opt/mExpress/projects/$PROJECT_NAME or /opt/mExpress/packages/$PROJECT_NAME"
  exit 1
fi

# Define report paths
OUTPUT_FILE="/opt/mExpress/docs/$PROJECT_NAME/_tests/TESTS_STATUS.md"
TEST_LIST_FILE="/opt/mExpress/docs/$PROJECT_NAME/_tests/PROJECT_TESTS_LIST.md"
LOGS_DIR="/opt/mExpress/tests/results/logs"
mkdir -p "$(dirname "$OUTPUT_FILE")"
mkdir -p "$LOGS_DIR"

# Check if test list file exists
if [ ! -f "$TEST_LIST_FILE" ]; then
  echo "Error: Test list file not found: $TEST_LIST_FILE"
  echo "Please run a_project_test_pre_calculation.sh first."
  exit 1
fi

# Initialize counters
total=0
pass=0
fail=0
timeout=0
skipped=0

# Initialize file type counters as global variables
declare -g js_tests=0
declare -g ts_tests=0
declare -g tsx_tests=0
declare -g jsx_tests=0

# Initialize component area counters
declare -g -A component_area_total=()
declare -g -A component_area_pass=()
declare -g -A component_area_fail=()

# Initialize test type counters
declare -g -A test_type_total=()
declare -g -A test_type_pass=()
declare -g -A test_type_fail=()

# Initialize priority level counters
declare -g -A priority_total=()
declare -g -A priority_pass=()
declare -g -A priority_fail=()

# Parse command line arguments
max_tests=-1
run_all=false
shuffle=false
priority_filter=""

for arg in "$@"; do
  case $arg in
    --max-tests=*)
      max_tests="${arg#*=}"
      ;;
    --all)
      run_all=true
      ;;
    --shuffle)
      shuffle=true
      ;;
    --priority=*)
      priority_filter="${arg#*=}"
      ;;
    *)
      echo "Unknown option: $arg"
      exit 1
      ;;
  esac
done

# Create the output file with header
cat > "$OUTPUT_FILE" << EOF
# ${PROJECT_NAME^} Project Test Status Report
*Last updated: $(date +%Y-%m-%d)*

This report shows test execution status and metrics for the ${PROJECT_NAME^} project.

Legend:
- ✅ - Test passes
- ❌ - Test fails
- ⏱️ - Test timed out
- ⏩ - Test skipped
- 📍 - Test is in project-specific location (correct)
- 🚚 - Test needs to be moved from centralized location
- 🔢 - Test has priority label (P0-P3)
- ❔ - Test missing priority label
- 🕒 - Test duration
- 🧪 - Test type (unit, integration, e2e)
- 📦 - Component area
- 🔍 - Error type (for failing tests)
- 🧩 - Test coverage percentage
- 📝 - JavaScript file (.js) - MIGRATION REQUIRED ⚠️
- 📘 - TypeScript file (.ts) - PREFERRED ✓
- 📗 - React TypeScript file (.tsx) - PREFERRED ✓
- 📙 - React JavaScript file (.jsx) - MIGRATION REQUIRED ⚠️
- 👯 - Duplicate test (same name in both JS and TS) - JS VERSION SHOULD BE REMOVED ⚠️

## Tests By Status (Running)

EOF

# Extract test list from file
readarray -t all_tests < <(grep -E '^[📍🚚][🔢❔][📝📘📗📙]' "$TEST_LIST_FILE" | sed 's/^.*🧪:[a-z]\+ 📦:[a-z]\+ \(\/.*\)$/\1/')

# Filter tests by priority if specified
if [ -n "$priority_filter" ]; then
  IFS=',' read -ra PRIORITIES <<< "$priority_filter"
  filtered_tests=()
  
  for test in "${all_tests[@]}"; do
    for pri in "${PRIORITIES[@]}"; do
      pri_pattern=$(echo "$pri" | tr '[:upper:]' '[:lower:]')
      if [[ "$test" =~ /p${pri_pattern: -1} ]]; then
        filtered_tests+=("$test")
        break
      fi
    done
  done
  
  all_tests=("${filtered_tests[@]}")
fi

# Shuffle tests if requested
if [ "$shuffle" = true ]; then
  readarray -t all_tests < <(printf "%s\n" "${all_tests[@]}" | shuf)
fi

# Limit tests if requested
if [ "$max_tests" -gt 0 ] && [ "${#all_tests[@]}" -gt "$max_tests" ]; then
  all_tests=("${all_tests[@]:0:$max_tests}")
fi

echo "🧪 Running ${#all_tests[@]} tests for ${PROJECT_NAME^} project..."

# Run tests one by one
for test_file in "${all_tests[@]}"; do
  # Extract icon statuses from TEST_LIST_FILE
  icons=$(grep -E "^[📍🚚][🔢❔][📝📘📗📙] 🧪:[a-z]+ 📦:[a-z]+ $test_file$" "$TEST_LIST_FILE" | awk '{print $1}')
  
  # Extract test type and component area
  test_type=$(grep -E "^[📍🚚][🔢❔][📝📘📗📙] 🧪:[a-z]+ 📦:[a-z]+ $test_file$" "$TEST_LIST_FILE" | sed -E 's/^[📍🚚][🔢❔][📝📘📗📙] 🧪:([a-z]+) 📦:[a-z]+ .*$/\1/')
  component_area=$(grep -E "^[📍🚚][🔢❔][📝📘📗📙] 🧪:[a-z]+ 📦:[a-z]+ $test_file$" "$TEST_LIST_FILE" | sed -E 's/^[📍🚚][🔢❔][📝📘📗📙] 🧪:[a-z]+ 📦:([a-z]+) .*$/\1/')
  
  # Determine file type
  if [[ "$test_file" =~ \.ts$ ]]; then
    ((ts_tests++))
  elif [[ "$test_file" =~ \.tsx$ ]]; then
    ((tsx_tests++))
  elif [[ "$test_file" =~ \.js$ ]]; then
    ((js_tests++))
  elif [[ "$test_file" =~ \.jsx$ ]]; then
    ((jsx_tests++))
  fi
  
  # Determine priority
  priority="unknown"
  if [[ "$test_file" =~ /p([0-3])/ ]]; then
    priority="P${BASH_REMATCH[1]}"
  fi
  
  # Update counters
  ((total++))
  component_area_total["$component_area"]=$((${component_area_total["$component_area"]:=0} + 1))
  test_type_total["$test_type"]=$((${test_type_total["$test_type"]:=0} + 1))
  priority_total["$priority"]=$((${priority_total["$priority"]:=0} + 1))
  
  # Prepare log file
  log_dir=$(dirname "$LOGS_DIR/${test_file}")
  mkdir -p "$log_dir"
  log_file="$LOGS_DIR/${test_file}_$(date +%Y%m%d_%H%M%S).log"
  
  # Determine test command based on file extension
  if [[ "$test_file" =~ \.(js|jsx)$ ]]; then
    test_cmd="npx jest --no-cache '$test_file'"
  else
    test_cmd="npx jest --preset=ts-jest --no-cache '$test_file'"
  fi
  
  # Run the test with timeout
  echo "🔍 Running: $test_file"
  start_time=$(date +%s)
  
  timeout 60 bash -c "$test_cmd" > "$log_file" 2>&1
  test_result=$?
  
  end_time=$(date +%s)
  duration=$((end_time - start_time))
  
  # Process test result
  status_emoji=""
  status_text=""
  error_type=""
  
  if [ $test_result -eq 124 ]; then
    status_emoji="⏱️"
    status_text="TIMEOUT"
    ((timeout++))
  elif [ $test_result -eq 0 ]; then
    status_emoji="✅"
    status_text="PASS"
    ((pass++))
    component_area_pass["$component_area"]=$((${component_area_pass["$component_area"]:=0} + 1))
    test_type_pass["$test_type"]=$((${test_type_pass["$test_type"]:=0} + 1))
    priority_pass["$priority"]=$((${priority_pass["$priority"]:=0} + 1))
  else
    status_emoji="❌"
    status_text="FAIL"
    ((fail++))
    component_area_fail["$component_area"]=$((${component_area_fail["$component_area"]:=0} + 1))
    test_type_fail["$test_type"]=$((${test_type_fail["$test_type"]:=0} + 1))
    priority_fail["$priority"]=$((${priority_fail["$priority"]:=0} + 1))
    
    # Determine error type
    if grep -q "TypeError" "$log_file"; then
      error_type="TypeError"
    elif grep -q "SyntaxError" "$log_file"; then
      error_type="SyntaxError"
    elif grep -q "ReferenceError" "$log_file"; then
      error_type="ReferenceError"
    elif grep -q "AssertionError" "$log_file"; then
      error_type="AssertionError"
    else
      error_type="UnknownError"
    fi
  fi
  
  # Determine test coverage (placeholder for now)
  coverage="~70%"
  coverage_text="🧩:$coverage"
  
  # Prepare error type text if applicable
  error_text=""
  if [ -n "$error_type" ]; then
    error_text="🔍:$error_type"
  fi
  
  # Write test result to report
  echo "$status_emoji$icons 🕒:${duration}s 🧪:$test_type 📦:$component_area $error_text $coverage_text $test_file | [log](${log_file#/opt/mExpress})" >> "$OUTPUT_FILE"
  
  # Update the output file with progress summary at specific points
  if [ $((total % 10)) -eq 0 ] || [ "$total" -eq "${#all_tests[@]}" ]; then
    # Calculate summary statistics
    if [ "$total" -gt 0 ]; then
      pass_percent=$((pass * 100 / total))
      fail_percent=$((fail * 100 / total))
      timeout_percent=$((timeout * 100 / total))
    else
      pass_percent=0
      fail_percent=0
      timeout_percent=0
    fi
    
    # Remove summary if it exists
    sed -i '/^## Test Execution Summary/,$d' "$OUTPUT_FILE"
    
    # Add updated summary
    cat >> "$OUTPUT_FILE" << EOF

## Test Execution Summary
| Status | Count | Percentage |
|--------|-------|------------|
| ✅ Pass | $pass | ${pass_percent}% |
| ❌ Fail | $fail | ${fail_percent}% |
| ⏱️ Timeout | $timeout | ${timeout_percent}% |
| Total | $total | 100% |

### Status by Component Area
| Component Area | Total | Pass | Fail | Pass Rate |
|----------------|-------|------|------|-----------|
EOF
    
    # Add component area stats
    for area in "${!component_area_total[@]}"; do
      area_total=${component_area_total["$area"]}
      area_pass=${component_area_pass["$area"]:=0}
      area_fail=${component_area_fail["$area"]:=0}
      if [ "$area_total" -gt 0 ]; then
        area_pass_rate=$((area_pass * 100 / area_total))
      else
        area_pass_rate=0
      fi
      echo "| $area | $area_total | $area_pass | $area_fail | ${area_pass_rate}% |" >> "$OUTPUT_FILE"
    done
    
    # Add test type stats
    cat >> "$OUTPUT_FILE" << EOF

### Status by Test Type
| Test Type | Total | Pass | Fail | Pass Rate |
|-----------|-------|------|------|-----------|
EOF
    
    for type in "${!test_type_total[@]}"; do
      type_total=${test_type_total["$type"]}
      type_pass=${test_type_pass["$type"]:=0}
      type_fail=${test_type_fail["$type"]:=0}
      if [ "$type_total" -gt 0 ]; then
        type_pass_rate=$((type_pass * 100 / type_total))
      else
        type_pass_rate=0
      fi
      echo "| $type | $type_total | $type_pass | $type_fail | ${type_pass_rate}% |" >> "$OUTPUT_FILE"
    done
    
    # Add priority stats
    cat >> "$OUTPUT_FILE" << EOF

### Status by Priority
| Priority | Total | Pass | Fail | Pass Rate |
|----------|-------|------|------|-----------|
EOF
    
    for pri in "${!priority_total[@]}"; do
      pri_total=${priority_total["$pri"]}
      pri_pass=${priority_pass["$pri"]:=0}
      pri_fail=${priority_fail["$pri"]:=0}
      if [ "$pri_total" -gt 0 ]; then
        pri_pass_rate=$((pri_pass * 100 / pri_total))
      else
        pri_pass_rate=0
      fi
      echo "| $pri | $pri_total | $pri_pass | $pri_fail | ${pri_pass_rate}% |" >> "$OUTPUT_FILE"
    done
    
    # Add file type stats
    cat >> "$OUTPUT_FILE" << EOF

### File Type Distribution
| File Type | Count | Status |
|-----------|-------|--------|
| TypeScript (.ts) | $ts_tests | PREFERRED ✓ |
| React TypeScript (.tsx) | $tsx_tests | PREFERRED ✓ |
| JavaScript (.js) | $js_tests | MIGRATION REQUIRED ⚠️ |
| React JavaScript (.jsx) | $jsx_tests | MIGRATION REQUIRED ⚠️ |

## Test Execution Progress
- Tests completed: $total/${#all_tests[@]} ($(( total * 100 / ${#all_tests[@]} ))%)
- Tests remaining: $(( ${#all_tests[@]} - total )) ($(( (${#all_tests[@]} - total) * 100 / ${#all_tests[@]} ))%)
- Estimated completion time: $(( (${#all_tests[@]} - total) * duration / 60 )) minutes

Last updated: $(date)
EOF
  fi
done

echo "✅ Test execution complete for ${PROJECT_NAME^} project!"
echo "📊 Test status report: $OUTPUT_FILE"

# Calculate final statistics
if [ "$total" -gt 0 ]; then
  pass_percent=$((pass * 100 / total))
  fail_percent=$((fail * 100 / total))
  timeout_percent=$((timeout * 100 / total))
else
  pass_percent=0
  fail_percent=0
  timeout_percent=0
fi

echo "📊 Test Statistics:"
echo "    Total: $total"
echo "    Pass: $pass (${pass_percent}%)"
echo "    Fail: $fail (${fail_percent}%)"
echo "    Timeout: $timeout (${timeout_percent}%)"