// This file is auto-generated by update-dashboard.js
// Do not edit this file directly - it will be overwritten

window.dashboardData = {
  "lastUpdated": "2025-03-03",
  "summary": {
    "total": 104,
    "passing": 34,
    "failing": 67,
    "hanging": 3,
    "skipped": 0
  },
  "byPriority": {
    "p0": {
      "total": 25,
      "passing": 21,
      "failing": 4,
      "success": 84
    },
    "p1": {
      "total": 21,
      "passing": 8,
      "failing": 13,
      "success": 38.1
    },
    "p2": {
      "total": 16,
      "passing": 5,
      "failing": 11,
      "success": 31.3
    },
    "p3": {
      "total": 17,
      "passing": 0,
      "failing": 14,
      "hanging": 3,
      "success": 0
    },
    "unclassified": {
      "total": 25,
      "passing": 0,
      "failing": 25,
      "success": 0
    }
  },
  "byLocation": {
    "canonical": {
      "total": 25,
      "passing": 0,
      "failing": 25,
      "success": 0
    },
    "needToMove": {
      "total": 79,
      "passing": 34,
      "failing": 42,
      "hanging": 3,
      "success": 43
    }
  },
  "byProject": {
    "core": {
      "total": 65,
      "passing": 34,
      "failing": 28,
      "hanging": 3,
      "success": 52.3
    },
    "montpc": {
      "total": 14,
      "passing": 0,
      "failing": 14,
      "success": 0
    },
    "ui": {
      "total": 2,
      "passing": 0,
      "failing": 2,
      "success": 0
    },
    "utils": {
      "total": 8,
      "passing": 0,
      "failing": 8,
      "success": 0
    },
    "unclassified": {
      "total": 15,
      "passing": 0,
      "failing": 15,
      "success": 0
    }
  },
  "recentFixes": [
    "Initial setup of test dashboard with accurate status reporting"
  ],
  "nextSteps": {
    "high": [
      {
        "title": "P0 Critical Tests",
        "detail": "",
        "bullets": [
          "Fix event-handler.test.ts in P0 priority",
          "Address failing MontPC frontend dashboard tests",
          "Fix customer detail component test"
        ]
      }
    ],
    "medium": [
      {
        "title": "Service Integration",
        "detail": "",
        "bullets": [
          "Fix catalog-event.service.test.ts",
          "Fix cross-service-auth.test.ts",
          "Address styling-consistency.test.tsx"
        ]
      },
      {
        "title": "Frontend Authentication",
        "detail": "",
        "bullets": [
          "Fix MontPC authentication component tests",
          "Implement proper mocking for auth context",
          "Address LoginForm, ProtectedRoute and RegisterForm components"
        ]
      }
    ],
    "low": [
      {
        "title": "Performance Tests",
        "detail": "",
        "bullets": [
          "Address P3 stress tests",
          "Fix hanging performance tests",
          "Implement database performance optimizations"
        ]
      }
    ]
  },
  "brqs": [
    {
      "id": "MEXP-2025-001-API",
      "name": "API Integration Phase",
      "tests": 3,
      "priority": "P0",
      "status": "in-progress",
      "progress": 33.3
    },
    {
      "id": "MEXP-2025-002-BE",
      "name": "Authentication & Security",
      "tests": 4,
      "priority": "P0",
      "status": "in-progress",
      "progress": 75
    },
    {
      "id": "MEXP-2025-003-BE",
      "name": "Message Queue System",
      "tests": 5,
      "priority": "P0",
      "status": "in-progress",
      "progress": 80
    },
    {
      "id": "MEXP-2025-004-BE",
      "name": "Core CRUD Functionality",
      "tests": 3,
      "priority": "P0",
      "status": "not-started",
      "progress": 0
    },
    {
      "id": "MEXP-2025-005-FE",
      "name": "UI Architecture",
      "tests": 1,
      "priority": "P1",
      "status": "not-started",
      "progress": 0
    },
    {
      "id": "MEXP-2025-006-API",
      "name": "Customer CRUD API",
      "tests": 3,
      "priority": "P0",
      "status": "not-started",
      "progress": 0
    },
    {
      "id": "MEXP-2025-007-BE",
      "name": "Service Integration Architecture",
      "tests": 9,
      "priority": "P0",
      "status": "in-progress",
      "progress": 66.7
    },
    {
      "id": "MEXP-2025-008-BE",
      "name": "Customer Management System",
      "tests": 2,
      "priority": "P0",
      "status": "in-progress",
      "progress": 100
    },
    {
      "id": "MEXP-2025-018-FE",
      "name": "Frontend Test Architecture",
      "tests": 1,
      "priority": "P2",
      "status": "not-started",
      "progress": 0
    },
    {
      "id": "MEXP-2025-024-INFRA",
      "name": "MVP Readiness",
      "tests": 3,
      "priority": "P3",
      "status": "not-started",
      "progress": 0
    },
    {
      "id": "MEXP-2025-025-INFRA",
      "name": "Infrastructure Simplification",
      "tests": 3,
      "priority": "P3",
      "status": "not-started",
      "progress": 0
    },
    {
      "id": "MEXP-2025-027-BE",
      "name": "Product Catalog",
      "tests": 3,
      "priority": "P1",
      "status": "not-started",
      "progress": 0
    },
    {
      "id": "MEXP-2025-030-API",
      "name": "External API Integrations",
      "tests": 3,
      "priority": "P1",
      "status": "not-started",
      "progress": 0
    },
    {
      "id": "MEXP-2025-031-API",
      "name": "Ringover Customer Management",
      "tests": 3,
      "priority": "P1",
      "status": "not-started",
      "progress": 0
    },
    {
      "id": "MEXP-2025-037-FULL",
      "name": "MVP Implementation",
      "tests": 3,
      "priority": "P3",
      "status": "not-started",
      "progress": 0
    },
    {
      "id": "MEXP-2025-040-FE",
      "name": "Dashboard Design",
      "tests": 1,
      "priority": "P2",
      "status": "not-started",
      "progress": 0
    },
    {
      "id": "MONT-2025-001-FULL",
      "name": "Customer Service Implementation",
      "tests": 2,
      "priority": "P0",
      "status": "in-progress",
      "progress": 0
    },
    {
      "id": "MONT-2025-002-FULL",
      "name": "Auth Service & Frontend",
      "tests": 5,
      "priority": "P1",
      "status": "not-started",
      "progress": 0
    },
    {
      "id": "MONT-2025-007-FULL",
      "name": "Emergency Recovery",
      "tests": 0,
      "priority": "P1",
      "status": "not-started",
      "progress": 0
    },
    {
      "id": "MONT-2025-032-API",
      "name": "External Integrations",
      "tests": 1,
      "priority": "P2",
      "status": "not-started",
      "progress": 0
    }
  ],
  "tests": [
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/integration/external-integration.update.test.ts",
      "shortPath": "packages/core/tests/integration/external-integration.update.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/api/connection-timeout.test.ts",
      "shortPath": "packages/core/tests/p0/api/connection-timeout.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/customer-management.test.ts",
      "shortPath": "packages/core/tests/p0/core/customer-management.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/event-handler.test.ts",
      "shortPath": "packages/core/tests/p0/core/event-handler.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/every.test.js",
      "shortPath": "packages/core/tests/p0/core/every.test.js",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/git-workflow.test.ts",
      "shortPath": "packages/core/tests/p0/core/git-workflow.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/istio-client.additional.test.ts",
      "shortPath": "packages/core/tests/p0/core/istio-client.additional.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/istio-client.test.ts",
      "shortPath": "packages/core/tests/p0/core/istio-client.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/login.api.test.ts",
      "shortPath": "packages/core/tests/p0/core/login.api.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/message-delivery-confirmation.test.ts",
      "shortPath": "packages/core/tests/p0/core/message-delivery-confirmation.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/message-queue-v2.test.ts",
      "shortPath": "packages/core/tests/p0/core/message-queue-v2.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/security.test.ts",
      "shortPath": "packages/core/tests/p0/core/security.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/service-discovery.test.ts",
      "shortPath": "packages/core/tests/p0/core/service-discovery.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/time-provider.test.ts",
      "shortPath": "packages/core/tests/p0/core/time-provider.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/transaction-rollback.test.ts",
      "shortPath": "packages/core/tests/p0/core/transaction-rollback.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/value-to-string.test.js",
      "shortPath": "packages/core/tests/p0/core/value-to-string.test.js",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/services/customer.service.test.ts",
      "shortPath": "packages/core/tests/p0/services/customer.service.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/services/debug-hiboutik.test.ts",
      "shortPath": "packages/core/tests/p0/services/debug-hiboutik.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/services/hiboutik.auth.test.ts",
      "shortPath": "packages/core/tests/p0/services/hiboutik.auth.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/services/hiboutik.service.test.ts",
      "shortPath": "packages/core/tests/p0/services/hiboutik.service.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/services/product.service.test.ts",
      "shortPath": "packages/core/tests/p0/services/product.service.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/services/ringover.service.test.ts",
      "shortPath": "packages/core/tests/p0/services/ringover.service.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/sync.service.test.ts",
      "shortPath": "packages/core/tests/p0/sync.service.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/projects/montpc_crm/frontend/tests/p0/components/dashboard.test.tsx",
      "shortPath": "projects/montpc_crm/frontend/tests/p0/components/dashboard.test.tsx",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "montpc"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/projects/montpc_crm/frontend/tests/p0/core/CustomerDetail.test.tsx",
      "shortPath": "projects/montpc_crm/frontend/tests/p0/core/CustomerDetail.test.tsx",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "montpc"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/api/retry-logic.test.ts",
      "shortPath": "packages/core/tests/p1/api/retry-logic.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/auth/permissions.test.ts",
      "shortPath": "packages/core/tests/p1/auth/permissions.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/auth/token-refresh.test.ts",
      "shortPath": "packages/core/tests/p1/auth/token-refresh.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/core/concurrent-modification.test.ts",
      "shortPath": "packages/core/tests/p1/core/concurrent-modification.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/core/pipeline.test.ts",
      "shortPath": "packages/core/tests/p1/core/pipeline.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/core/queue-persistence.test.ts",
      "shortPath": "packages/core/tests/p1/core/queue-persistence.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p1/frontend/components/styling-consistency.test.tsx",
      "shortPath": "packages/core/tests/p1/frontend/components/styling-consistency.test.tsx",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/frontend/component-tests.test.js",
      "shortPath": "packages/core/tests/p1/frontend/component-tests.test.js",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p1/services/catalog-event.service.test.ts",
      "shortPath": "packages/core/tests/p1/services/catalog-event.service.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/services/category-events.test.ts",
      "shortPath": "packages/core/tests/p1/services/category-events.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p1/services/cross-service-auth.test.ts",
      "shortPath": "packages/core/tests/p1/services/cross-service-auth.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/services/customer-validation.service.test.ts",
      "shortPath": "packages/core/tests/p1/services/customer-validation.service.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/services/product-events.test.ts",
      "shortPath": "packages/core/tests/p1/services/product-events.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/services/ringover.customer.test.ts",
      "shortPath": "packages/core/tests/p1/services/ringover.customer.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/services/service-deployment.test.ts",
      "shortPath": "packages/core/tests/p1/services/service-deployment.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/services/service-mesh.test.ts",
      "shortPath": "packages/core/tests/p1/services/service-mesh.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/services/sync.customer.test.ts",
      "shortPath": "packages/core/tests/p1/services/sync.customer.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/projects/montpc_crm/frontend/tests/p1/auth/login.ui.test.tsx",
      "shortPath": "projects/montpc_crm/frontend/tests/p1/auth/login.ui.test.tsx",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "montpc"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/projects/montpc_crm/frontend/tests/p1/features/CustomerRoutes.test.tsx",
      "shortPath": "projects/montpc_crm/frontend/tests/p1/features/CustomerRoutes.test.tsx",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "montpc"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/projects/montpc_crm/tests/frontend/p0/components/auth/LoginForm.test.tsx",
      "shortPath": "projects/montpc_crm/tests/frontend/p0/components/auth/LoginForm.test.tsx",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "montpc"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/projects/montpc_crm/tests/frontend/p0/components/auth/ProtectedRoute.test.tsx",
      "shortPath": "projects/montpc_crm/tests/frontend/p0/components/auth/ProtectedRoute.test.tsx",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "montpc"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p2/api/edge-cases.test.ts",
      "shortPath": "packages/core/tests/p2/api/edge-cases.test.ts",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p2/auth/multi-login.test.ts",
      "shortPath": "packages/core/tests/p2/auth/multi-login.test.ts",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/bulk-operations.test.ts",
      "shortPath": "packages/core/tests/p2/core/bulk-operations.test.ts",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/called-in-order.test.js",
      "shortPath": "packages/core/tests/p2/core/called-in-order.test.js",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/class-name.test.js",
      "shortPath": "packages/core/tests/p2/core/class-name.test.js",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/copy-prototype-methods.test.js",
      "shortPath": "packages/core/tests/p2/core/copy-prototype-methods.test.js",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/customer.unit.test.ts",
      "shortPath": "packages/core/tests/p2/core/customer.unit.test.ts",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/function-name.test.js",
      "shortPath": "packages/core/tests/p2/core/function-name.test.js",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/message-queue-recovery.test.js",
      "shortPath": "packages/core/tests/p2/core/message-queue-recovery.test.js",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/order-by-first-call.test.js",
      "shortPath": "packages/core/tests/p2/core/order-by-first-call.test.js",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/product.test.ts",
      "shortPath": "packages/core/tests/p2/core/product.test.ts",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/type-of.test.js",
      "shortPath": "packages/core/tests/p2/core/type-of.test.js",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p2/frontend/components/mobile/responsive-layout.test.tsx",
      "shortPath": "packages/core/tests/p2/frontend/components/mobile/responsive-layout.test.tsx",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p2/services/data-consistency.test.ts",
      "shortPath": "packages/core/tests/p2/services/data-consistency.test.ts",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/projects/montpc_crm/tests/frontend/p0/components/auth/RegisterForm.test.tsx",
      "shortPath": "projects/montpc_crm/tests/frontend/p0/components/auth/RegisterForm.test.tsx",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "montpc"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/projects/montpc_crm/tests/frontend/p2/components/dashboard/ActionShortcuts.test.tsx",
      "shortPath": "projects/montpc_crm/tests/frontend/p2/components/dashboard/ActionShortcuts.test.tsx",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "montpc"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p3/api/basic-stress.test.ts",
      "shortPath": "packages/core/tests/p3/api/basic-stress.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p3/api/simplified-rate-limit.test.ts",
      "shortPath": "packages/core/tests/p3/api/simplified-rate-limit.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p3/api/stress-tests.test.ts",
      "shortPath": "packages/core/tests/p3/api/stress-tests.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "hanging",
      "path": "/opt/mExpress/packages/core/tests/p3/auth/performance.test.ts",
      "shortPath": "packages/core/tests/p3/auth/performance.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p3/core/message-queue-stress.test.ts",
      "shortPath": "packages/core/tests/p3/core/message-queue-stress.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p3/frontend/accessibility/component-accessibility.test.tsx",
      "shortPath": "packages/core/tests/p3/frontend/accessibility/component-accessibility.test.tsx",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "hanging",
      "path": "/opt/mExpress/packages/core/tests/p3/infrastructure/database-performance.test.ts",
      "shortPath": "packages/core/tests/p3/infrastructure/database-performance.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p3/models/customer.integration.test.ts",
      "shortPath": "packages/core/tests/p3/models/customer.integration.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "hanging",
      "path": "/opt/mExpress/packages/core/tests/p3/services/load-balancer.test.ts",
      "shortPath": "packages/core/tests/p3/services/load-balancer.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/unit/validation/customerValidation.test.ts",
      "shortPath": "packages/core/tests/unit/validation/customerValidation.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "tests/packages/core/integration/infrastructure/container-orchestrator-integration.test.ts",
      "shortPath": "tests/packages/core/integration/infrastructure/container-orchestrator-integration.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "tests/packages/core/integration/infrastructure/external-integration.core.test.ts",
      "shortPath": "tests/packages/core/integration/infrastructure/external-integration.core.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "tests/packages/core/integration/infrastructure/pipeline-integration.test.ts",
      "shortPath": "tests/packages/core/integration/infrastructure/pipeline-integration.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "tests/packages/core/unit/core/message-queue/message-state-manager.test.ts",
      "shortPath": "tests/packages/core/unit/core/message-queue/message-state-manager.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "tests/packages/core/unit/frontend/components/TestExecutionPanel.test.tsx",
      "shortPath": "tests/packages/core/unit/frontend/components/TestExecutionPanel.test.tsx",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "tests/packages/core/unit/reconciliation-tools/componentScanner.test.ts",
      "shortPath": "tests/packages/core/unit/reconciliation-tools/componentScanner.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "tests/packages/core/unit/reconciliation-tools/matrixTracker.test.ts",
      "shortPath": "tests/packages/core/unit/reconciliation-tools/matrixTracker.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "tests/packages/utils/unit/lib/monitoring/monitoring.system.test.ts",
      "shortPath": "tests/packages/utils/unit/lib/monitoring/monitoring.system.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "utils"
    },
    {
      "status": "failing",
      "path": "tests/packages/utils/unit/lib/resilience/circuit-breaker.test.ts",
      "shortPath": "tests/packages/utils/unit/lib/resilience/circuit-breaker.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "utils"
    },
    {
      "status": "failing",
      "path": "tests/packages/utils/unit/lib/resilience/rate-limiter.resilience.test.ts",
      "shortPath": "tests/packages/utils/unit/lib/resilience/rate-limiter.resilience.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "utils"
    },
    {
      "status": "failing",
      "path": "tests/packages/utils/unit/lib/resilience/retry-strategy.error.test.ts",
      "shortPath": "tests/packages/utils/unit/lib/resilience/retry-strategy.error.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "utils"
    },
    {
      "status": "failing",
      "path": "tests/packages/utils/unit/lib/resilience/retry-strategy.test.ts",
      "shortPath": "tests/packages/utils/unit/lib/resilience/retry-strategy.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "utils"
    },
    {
      "status": "failing",
      "path": "tests/packages/utils/unit/utils/logger.test.ts",
      "shortPath": "tests/packages/utils/unit/utils/logger.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "utils"
    },
    {
      "status": "failing",
      "path": "tests/packages/utils/unit/utils/moduleCheck.test.ts",
      "shortPath": "tests/packages/utils/unit/utils/moduleCheck.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "utils"
    },
    {
      "status": "failing",
      "path": "tests/packages/utils/unit/utils/monitoring.collector.test.ts",
      "shortPath": "tests/packages/utils/unit/utils/monitoring.collector.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "utils"
    },
    {
      "status": "failing",
      "path": "tests/packages/utils/unit/utils/rate-limiter.utils.test.ts",
      "shortPath": "tests/packages/utils/unit/utils/rate-limiter.utils.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "utils"
    },
    {
      "status": "failing",
      "path": "tests/projects/montpc_crm/frontend/unit/api/interceptors/auth.interceptor.test.ts",
      "shortPath": "tests/projects/montpc_crm/frontend/unit/api/interceptors/auth.interceptor.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "montpc"
    },
    {
      "status": "failing",
      "path": "tests/projects/montpc_crm/frontend/unit/api/interceptors/error.interceptor.test.ts",
      "shortPath": "tests/projects/montpc_crm/frontend/unit/api/interceptors/error.interceptor.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "montpc"
    },
    {
      "status": "failing",
      "path": "tests/projects/montpc_crm/frontend/unit/api/interceptors/index.test.ts",
      "shortPath": "tests/projects/montpc_crm/frontend/unit/api/interceptors/index.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "montpc"
    },
    {
      "status": "failing",
      "path": "tests/projects/montpc_crm/frontend/unit/api/services/auth.service.test.ts",
      "shortPath": "tests/projects/montpc_crm/frontend/unit/api/services/auth.service.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "montpc"
    },
    {
      "status": "failing",
      "path": "tests/projects/montpc_crm/frontend/unit/api/services/customers.service.test.ts",
      "shortPath": "tests/projects/montpc_crm/frontend/unit/api/services/customers.service.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "montpc"
    },
    {
      "status": "failing",
      "path": "tests/projects/montpc_crm/frontend/unit/api/services/products.service.test.ts",
      "shortPath": "tests/projects/montpc_crm/frontend/unit/api/services/products.service.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "montpc"
    },
    {
      "status": "failing",
      "path": "tests/projects/montpc_crm/frontend/unit/components/customers/CustomerList.test.tsx",
      "shortPath": "tests/projects/montpc_crm/frontend/unit/components/customers/CustomerList.test.tsx",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "montpc"
    },
    {
      "status": "failing",
      "path": "tests/projects/montpc_crm/frontend/unit/components.test.tsx",
      "shortPath": "tests/projects/montpc_crm/frontend/unit/components.test.tsx",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "montpc"
    },
    {
      "status": "failing",
      "path": "tests/projects/montpc_crm/frontend/unit/hooks/useDebounce.test.ts",
      "shortPath": "tests/projects/montpc_crm/frontend/unit/hooks/useDebounce.test.ts",
      "priority": "unclassified",
      "location": "📍",
      "locationType": "canonical",
      "project": "montpc"
    }
  ]
};