// This file is auto-generated by update-dashboard.js
// Do not edit this file directly - it will be overwritten

window.dashboardData = {
  "lastUpdated": "2025-03-10",
  "summary": {
    "total": 169,
    "passing": 68,
    "failing": 99,
    "hanging": 2,
    "skipped": 0
  },
  "byPriority": {
    "p0": {
      "total": 71,
      "passing": 71,
      "failing": 0,
      "success": 100
    },
    "p1": {
      "total": 38,
      "passing": 38,
      "failing": 0,
      "success": 100
    },
    "p2": {
      "total": 12,
      "passing": 5,
      "failing": 7,
      "success": 41.7
    },
    "p3": {
      "total": 26,
      "passing": 11,
      "failing": 13,
      "hanging": 2,
      "success": 42.3
    }
  },
  "byLocation": {
    "canonical": {
      "total": 28,
      "passing": 0,
      "failing": 28,
      "success": 0
    },
    "needToMove": {
      "total": 141,
      "passing": 68,
      "failing": 71,
      "hanging": 2,
      "success": 48.2
    }
  },
  "byProject": {
    "core": {
      "total": 111,
      "passing": 48,
      "failing": 62,
      "hanging": 1,
      "success": 43.2
    },
    "montpc": {
      "total": 36,
      "passing": 10,
      "failing": 26,
      "hanging": 0,
      "success": 27.8
    },
    "ui": {
      "total": 4,
      "passing": 2,
      "failing": 2,
      "hanging": 0,
      "success": 50
    },
    "utils": {
      "total": 18,
      "passing": 8,
      "failing": 9,
      "hanging": 1,
      "success": 44.4
    }
  },
  "recentFixes": [
    "Fixed Ringover Customer Management tests (MEXP-2025-031-API)",
    "Fixed MontPC auth component tests (LoginForm, ProtectedRoute, RegisterForm)",
    "Fixed CustomerDetail component with proper type handling and adapter pattern",
    "Fixed Dashboard component test (MEXP-2025-040-FE)",
    "Fixed utility functions implementation (every.js and value-to-string.js)",
    "Implemented IstioClient with traffic management and testing features",
    "Fixed hiboutik service tests with proper mocking and retry logic",
    "Added rate limiting implementation for API service tests",
    "Fixed auth service tests and login tests (MONT-2025-002-FULL)",
    "Added proper skipping for Core CRUD tests (MEXP-2025-004-BE)"
  ],
  "nextSteps": {
    "high": [
      {
        "title": "Message Queue P1 Tests",
        "detail": "",
        "bullets": [
          "Implement queue persistence adapter",
          "Verify message-queue-v2.test.ts in p1 folder"
        ]
      },
      {
        "title": "UI Component Testing",
        "detail": "",
        "bullets": [
          "Fix TestExecutionPanel.test.tsx",
          "Implement React Testing Library setup",
          "Address hanging pipeline-integration tests"
        ]
      }
    ],
    "medium": [
      {
        "title": "Core Utilities",
        "detail": "(P2)",
        "bullets": [
          "Update JS utility tests (called-in-order, class-name, copy-prototype-methods)",
          "Fix message-queue-recovery.test.ts"
        ]
      },
      {
        "title": "P3 Performance Tests",
        "detail": "",
        "bullets": [
          "Fix stress-tests.test.ts",
          "Address hanging auth/performance.test.ts",
          "Fix database-performance.test.ts timing issues"
        ]
      },
      {
        "title": "Event System",
        "detail": "",
        "bullets": [
          "Fix category-events.test.ts and product-events.test.ts",
          "Fix message-queue-stress.test.ts",
          "Create event adapter implementation"
        ]
      }
    ],
    "low": [
      {
        "title": "Infrastructure Tests",
        "detail": "",
        "bullets": [
          "Fix istio-client.test.ts in P3",
          "Address remaining P2 utility tests",
          "Optimize test performance for CI pipeline"
        ]
      }
    ]
  },
  "brqs": [
    {
      "id": "MEXP-2025-001-API",
      "name": "API Integration Phase",
      "tests": 3,
      "priority": "P0",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-006-API",
      "name": "Customer CRUD API",
      "tests": 3,
      "priority": "P0",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-008-BE",
      "name": "Customer Management System",
      "tests": 2,
      "priority": "P0",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-003-BE",
      "name": "Message Queue System",
      "tests": 5,
      "priority": "P0",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-002-BE",
      "name": "Authentication & Security",
      "tests": 4,
      "priority": "P0",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-027-BE",
      "name": "Product Catalog",
      "tests": 3,
      "priority": "P1",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-037-FULL",
      "name": "MVP Implementation",
      "tests": 3,
      "priority": "P3",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-005-FE",
      "name": "UI Architecture",
      "tests": 1,
      "priority": "P1",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MONT-2025-001-FULL",
      "name": "Customer Service Implementation",
      "tests": 1,
      "priority": "P0",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-030-API",
      "name": "External API Integrations",
      "tests": 3,
      "priority": "P1",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-031-API",
      "name": "Ringover Customer Management",
      "tests": 3,
      "priority": "P1",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-007-BE",
      "name": "Service Integration Architecture",
      "tests": 9,
      "priority": "P0",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-004-BE",
      "name": "Core CRUD Functionality",
      "tests": 3,
      "priority": "P0",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-024-INFRA",
      "name": "MVP Readiness",
      "tests": 1,
      "priority": "P3",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-025-INFRA-A",
      "name": "Infrastructure Simplification Pt.1",
      "tests": "N/A",
      "priority": "P3",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MONT-2025-002-FULL",
      "name": "Auth Service & Frontend",
      "tests": 2,
      "priority": "P1",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-002-FE",
      "name": "Frontend Component Research",
      "tests": 1,
      "priority": "P1",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MONT-2025-032-API",
      "name": "External Integrations",
      "tests": 1,
      "priority": "P2",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-040-FE",
      "name": "Dashboard Design",
      "tests": 1,
      "priority": "P2",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-018-FE",
      "name": "Frontend Test Architecture",
      "tests": 1,
      "priority": "P2",
      "status": "complete",
      "progress": 100
    },
    {
      "id": "MEXP-2025-025-INFRA-B",
      "name": "Infrastructure Simplification Pt.2",
      "tests": 3,
      "priority": "P3",
      "status": "not-started",
      "progress": 0
    },
    {
      "id": "MONT-2025-007-FULL",
      "name": "Emergency Recovery",
      "tests": 0,
      "priority": "P1",
      "status": "not-started",
      "progress": 0
    }
  ],
  "tests": [
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/api/connection-timeout.test.ts",
      "shortPath": "packages/core/tests/p0/api/connection-timeout.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/customer-management.test.ts",
      "shortPath": "packages/core/tests/p0/core/customer-management.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/event-handler.test.ts",
      "shortPath": "packages/core/tests/p0/core/event-handler.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/every.test.js",
      "shortPath": "packages/core/tests/p0/core/every.test.js",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/git-workflow.test.ts",
      "shortPath": "packages/core/tests/p0/core/git-workflow.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/istio-client.additional.test.ts",
      "shortPath": "packages/core/tests/p0/core/istio-client.additional.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/istio-client.test.ts",
      "shortPath": "packages/core/tests/p0/core/istio-client.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/login.test.ts",
      "shortPath": "packages/core/tests/p0/core/login.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/message-delivery-confirmation.test.ts",
      "shortPath": "packages/core/tests/p0/core/message-delivery-confirmation.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/message-queue-v2.test.ts",
      "shortPath": "packages/core/tests/p0/core/message-queue-v2.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/message-state-manager.test.ts",
      "shortPath": "packages/core/tests/p0/core/message-state-manager.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/security.test.ts",
      "shortPath": "packages/core/tests/p0/core/security.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/service-discovery.test.ts",
      "shortPath": "packages/core/tests/p0/core/service-discovery.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/time-provider.test.ts",
      "shortPath": "packages/core/tests/p0/core/time-provider.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/transaction-rollback.test.ts",
      "shortPath": "packages/core/tests/p0/core/transaction-rollback.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/core/value-to-string.test.js",
      "shortPath": "packages/core/tests/p0/core/value-to-string.test.js",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/hiboutik.service.test.ts",
      "shortPath": "packages/core/tests/p0/hiboutik.service.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/services/customer.service.test.ts",
      "shortPath": "packages/core/tests/p0/services/customer.service.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/services/debug-hiboutik.test.ts",
      "shortPath": "packages/core/tests/p0/services/debug-hiboutik.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/services/hiboutik.auth.test.ts",
      "shortPath": "packages/core/tests/p0/services/hiboutik.auth.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/services/hiboutik.service.test.ts",
      "shortPath": "packages/core/tests/p0/services/hiboutik.service.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/services/product.service.test.ts",
      "shortPath": "packages/core/tests/p0/services/product.service.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/services/ringover.service.test.ts",
      "shortPath": "packages/core/tests/p0/services/ringover.service.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p0/sync.service.test.ts",
      "shortPath": "packages/core/tests/p0/sync.service.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/projects/montpc_crm/frontend/tests/p0/components/dashboard.test.tsx",
      "shortPath": "projects/montpc_crm/frontend/tests/p0/components/dashboard.test.tsx",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "montpc"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/projects/montpc_crm/frontend/tests/p0/core/CustomerDetail.test.tsx",
      "shortPath": "projects/montpc_crm/frontend/tests/p0/core/CustomerDetail.test.tsx",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "montpc"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/projects/montpc_crm/tests/frontend/p0/api/interceptors/auth.interceptor.test.ts",
      "shortPath": "projects/montpc_crm/tests/frontend/p0/api/interceptors/auth.interceptor.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "montpc"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/projects/montpc_crm/tests/frontend/p0/api/services/auth.service.test.ts",
      "shortPath": "projects/montpc_crm/tests/frontend/p0/api/services/auth.service.test.ts",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "montpc"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/projects/montpc_crm/tests/frontend/p0/components/auth/LoginForm.test.tsx",
      "shortPath": "projects/montpc_crm/tests/frontend/p0/components/auth/LoginForm.test.tsx",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "montpc"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/projects/montpc_crm/tests/frontend/p0/components/auth/ProtectedRoute.test.tsx",
      "shortPath": "projects/montpc_crm/tests/frontend/p0/components/auth/ProtectedRoute.test.tsx",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "montpc"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/projects/montpc_crm/tests/frontend/p0/components/auth/RegisterForm.test.tsx",
      "shortPath": "projects/montpc_crm/tests/frontend/p0/components/auth/RegisterForm.test.tsx",
      "priority": "p0",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "montpc"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/api/retry-logic.test.ts",
      "shortPath": "packages/core/tests/p1/api/retry-logic.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/auth/permissions.test.ts",
      "shortPath": "packages/core/tests/p1/auth/permissions.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/auth/token-refresh.test.ts",
      "shortPath": "packages/core/tests/p1/auth/token-refresh.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/core/concurrent-modification.test.ts",
      "shortPath": "packages/core/tests/p1/core/concurrent-modification.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/core/external-integration.test.ts",
      "shortPath": "packages/core/tests/p1/core/external-integration.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/core/message-state-manager.test.ts",
      "shortPath": "packages/core/tests/p1/core/message-state-manager.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/core/pipeline.test.ts",
      "shortPath": "packages/core/tests/p1/core/pipeline.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/core/queue-persistence.test.ts",
      "shortPath": "packages/core/tests/p1/core/queue-persistence.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/core/ringover.customer.test.ts",
      "shortPath": "packages/core/tests/p1/core/ringover.customer.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/core/sync.customer.test.ts",
      "shortPath": "packages/core/tests/p1/core/sync.customer.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p1/core/TestExecutionPanel.test.tsx",
      "shortPath": "packages/core/tests/p1/core/TestExecutionPanel.test.tsx",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/core/time-provider.test.ts",
      "shortPath": "packages/core/tests/p1/core/time-provider.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/services/category-events.test.ts",
      "shortPath": "packages/core/tests/p1/services/category-events.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/services/customer.service.test.ts",
      "shortPath": "packages/core/tests/p1/services/customer.service.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p1/services/customer-validation.service.test.ts",
      "shortPath": "packages/core/tests/p1/services/customer-validation.service.test.ts",
      "priority": "p1",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p2/api/edge-cases.test.ts",
      "shortPath": "packages/core/tests/p2/api/edge-cases.test.ts",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p2/auth/multi-login.test.ts",
      "shortPath": "packages/core/tests/p2/auth/multi-login.test.ts",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/bulk-operations.test.ts",
      "shortPath": "packages/core/tests/p2/core/bulk-operations.test.ts",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/called-in-order.test.js",
      "shortPath": "packages/core/tests/p2/core/called-in-order.test.js",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/class-name.test.js",
      "shortPath": "packages/core/tests/p2/core/class-name.test.js",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/copy-prototype-methods.test.js",
      "shortPath": "packages/core/tests/p2/core/copy-prototype-methods.test.js",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/customer.test.ts",
      "shortPath": "packages/core/tests/p2/core/customer.test.ts",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/function-name.test.js",
      "shortPath": "packages/core/tests/p2/core/function-name.test.js",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/message-queue-recovery.test.ts",
      "shortPath": "packages/core/tests/p2/core/message-queue-recovery.test.ts",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p2/core/product.test.ts",
      "shortPath": "packages/core/tests/p2/core/product.test.ts",
      "priority": "p2",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p3/api/basic-stress.test.ts",
      "shortPath": "packages/core/tests/p3/api/basic-stress.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p3/api/simplified-rate-limit.test.ts",
      "shortPath": "packages/core/tests/p3/api/simplified-rate-limit.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p3/api/stress-tests.test.ts",
      "shortPath": "packages/core/tests/p3/api/stress-tests.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "hanging",
      "path": "/opt/mExpress/packages/core/tests/p3/auth/performance.test.ts",
      "shortPath": "packages/core/tests/p3/auth/performance.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p3/core/category-events.test.ts",
      "shortPath": "packages/core/tests/p3/core/category-events.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/p3/core/customer-management.test.ts",
      "shortPath": "packages/core/tests/p3/core/customer-management.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p3/core/message-queue-stress.test.ts",
      "shortPath": "packages/core/tests/p3/core/message-queue-stress.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p3/core/product-events.test.ts",
      "shortPath": "packages/core/tests/p3/core/product-events.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "hanging",
      "path": "/opt/mExpress/packages/core/tests/p3/infrastructure/database-performance.test.ts",
      "shortPath": "packages/core/tests/p3/infrastructure/database-performance.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "failing",
      "path": "/opt/mExpress/packages/core/tests/p3/infrastructure/istio-client.test.ts",
      "shortPath": "packages/core/tests/p3/infrastructure/istio-client.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/integration/external-integration.test.ts",
      "shortPath": "packages/core/tests/integration/external-integration.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    },
    {
      "status": "passing",
      "path": "/opt/mExpress/packages/core/tests/integration/external-integration.update.test.ts",
      "shortPath": "packages/core/tests/integration/external-integration.update.test.ts",
      "priority": "p3",
      "location": "🔄",
      "locationType": "needs-moving",
      "project": "core"
    }
  ]
};