server {
    listen 80;
    listen [::]:80;
    server_name montpc.com;

    root /var/www/montpc.com;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Add simple cache headers for static assets
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg)$ {
        expires 30d;
        add_header Cache-Control "public";
    }
}